#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage $0 <filename>[.svg] " 
    exit 1
fi   
file=$(basename $1)
file=${file/.svg/}
inkscape --export-overwrite --export-filename  ${file}.{svg,pdf}
echo "pdf is in ${file}.pdf"

