#!/bin/bash

echo remove all latex disposables

rm -f  *.amc *.aux *.lo? *~ *.out *.toc *.snm *.nav \
   *.vrb *.bbl *.blg *.url *.up? *.xy
rm -f $(basename $(pwd))*.{pdf,pdfpc} 
rm -fr ./out

dirdoc=$(basename $(readlink -f .))
for i in ${dirdoc}*.{pdf,pdfpc}; do
	rm -f $i
	echo removed $i
done

for i in $(dirname .)*.{pdf,pdfpc} ; do
    if [[ -e $(basename $i .pdf).tex ]] ; then
	rm -f $i
	echo removed $i
    fi
done
       

