= SVN_Commit
:showtitle:

*Name* {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp}|  SVN_Commit +
*Actor* {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {sp}| Student +
*Description* {nbsp} {nbsp} {sp} | The svn commit process for the Student user. +
*Pre-condition* | Student is logged in the versioning system +

*Scenario* +
{nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp}1. Actor commits selected files. +
{nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp}2. System send a trigger to Fontys Venlo SVN server. +
{nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp}3. System sets building flag in publishing environment and puts the files in a queue. +
{nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp}4. System runs the comitted files through a build process. +
{nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp}5. System publishes files. +
{nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp}6. Actor has commited his files. +

*Result*
{nbsp} {nbsp}  The actor has committed his files. +

*Exceptions* 1 The actor's credentials were invalid. +
{nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} {nbsp} 1.1 Use case ends here.